spring:
  datasource:
    url: jdbc:postgresql://db:5432/url_shortener_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: url_shortener_db

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: url_shortener_db

springwebapp:
  security:
    secret_key: ${SECRET_KEY}
    expiration_time: ${EXPIRATION_TIME}