package org.forestwizard.urlshortener.status;

public enum Status {
    OK,
    UNIMPLEMENTED,
    UNAUTHORIZED_REQUEST,
    REQUEST_BODY_BAD_OR_MISSING,
    NOT_FOUND,
    SUCH_URL_NOT_EXISTS,
    THE_URL_IS_EXPIRED,
    SUCH_USER_ALREADY_EXISTS,
    INVALID_USERNAME_OR_PASSWORD,

    USERNAME_CANNOT_BE_NULL,
    PASSWORD_CANNOT_BE_NULL,
    INVALID_USERNAME_LENGTH,
    INVALID_PASSWORD_LENGTH,
    PASSWORD_REQUIREMENTS_UNSATISFIED,
    REGISTER_INTERNAL_ERROR,

    SESSION_EXPIRED,
    SESSION_MALFORMED,
    SESSION_INTERNAL_ERROR,
    ACCESS_DENIED,

    ORIGINAL_URL_CANNOT_BE_NULL,
    ORIGINAL_URL_CANNOT_BE_EMPTY,
    INVALID_ORIGINAL_URL_FORMAT,
    INVALID_URL_EXPIRATION_TIME,
    URL_EXPIRATION_TIME_CANNOT_BE_NULL,
    URL_GENERATION_FAILED
}
