package org.forestwizard.urlshortener.status;

public enum Status {
    OK,
    UNIMPLEMENTED,

    REQUEST_BODY_BAD_OR_MISSING,
    NOT_FOUND,
    SUCH_URL_NOT_EXISTS,
    THE_URL_IS_EXPIRED,
    SUCH_USER_ALREADY_EXISTS,
    SUCH_USER_NOT_EXISTS,

    USERNAME_CANNOT_BE_NULL,
    PASSWORD_CANNOT_BE_NULL,
    INVALID_PASSWORD,
    INVALID_USERNAME_LENGTH,
    INVALID_PASSWORD_LENGTH,
    PASSWORD_REQUIREMENTS_UNSATISFIED,

    SESSION_EXPIRED,

    ORIGINAL_URL_CANNOT_BE_NULL,
    ORIGINAL_URL_CANNOT_BE_EMPTY,
    INVALID_ORIGINAL_URL_FORMAT,
    INVALID_URL_EXPIRATION_TIME,
    URL_EXPIRATION_TIME_CANNOT_BE_NULL
}
